spring:
  application:
    name: URL-Shortening-Service
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  base-url: ${BASE_URL}