spring:
  application:
    name: URL-Shortening-Service
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  base-url: ${BASE_URL:localhost:8080/}